---
  - name: create aws ec2 launch configuration
    ec2_lc:
      name: Demo-ASG-LC
      key_name: "{{key_name}}"
      security_groups: ["{{ec2group.group_id}}"]
      instance_type: "{{instance_type}}"
      image_id: "{{image}}"
      region: "{{region}}"
      assign_public_ip: yes
      state: present
    register: ec2lc 
  - name: create aws ec2 auto scaler
    ec2_asg:
      name: "Demo-ASG"
      min_size: 1
      max_size: 5
      launch_config_name: Demo-ASG-LC
      replace_all_instances: false
      wait_for_instances: false
      load_balancers: ["Demo-ASG-ELB"]
      health_check_type: ELB
      vpc_zone_identifier: ["{{ec2vpc.subnets[0].id}}"]
      tags: 
        - env: "dev"
      region: "{{region}}"
      state: present
    register: ec2asg
  - name: define aws ec2 auto scale up policy
    ec2_scaling_policy:
      name: "Demo-ASG-Scale-Up"
      asg_name: "Demo-ASG"
      scaling_adjustment: 1
      min_adjustment_step: 1
      adjustment_type: "ChangeInCapacity"
      cooldown: 3000
      region: "{{region}}"
      state: present
    register: ec2asgpolicy
  - name: define aws ec2 auto scaling alarm/trigger
    ec2_metric_alarm:
      name: "Demo-ASG-CPU-high-alarm"
      alarm_actions: ["{{ ec2asgpolicy.arn }}"]
      dimensions: {"AutoScalingGroupName":"Demo-ASG"}
      metric: "CPUUtilization"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: ">="
      threshold: 90.0
      unit: "Percent"
      period: 60
      evaluation_periods: 2
      region: "{{region}}"
      state: present
    register: ec2asgalarm