---
  - name: create elastic load balancer (elb)
    ec2_elb_lb:
      name: "Demo-ASG-ELB"
      subnets: ["{{ec2vpc.subnets[0].id}}"]
      region: "{{region}}"
      security_group_ids: ["{{ec2group.group_id}}", "{{ec2elbgroup.group_id}}"]
      health_check:
        ping_protocol: http
        ping_port: 8080
        ping_path: "/"
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 2
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 8080
      state: present
    register: ec2elb