---
- name: prepare cloud infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ec2_access_key: AKIAIVOD33X45YM5X6DQ
    ec2_secret_key: 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
    key_name: vineet-michael-ansible
    instance_type: t2.micro
    image: ami-d05e75b8
    region: us-east-1
  tasks:
  - name: install boto
    pip: name=boto
  - name: create a security group
    ec2_group:
      state: present
      name: vineet-is-secure
      description: vineet is a hulk bouncer!
      region: "{{region}}"
  - name: create a virtual private cloud (vpc)
    ec2_vpc:
      state: present
      cidr_block: 10.0.0.0/16
      internet_gateway: True
      region: "{{region}}"
      resource_tags: { "env": "dev" }
      subnets:
        - cidr: 10.0.1.0/24
          az: us-east-1a
          resource_tags: { "env":"dev", "tier" : "web" }
        - cidr: 10.0.2.0/24
          az: us-east-1c
          resource_tags: { "env":"dev", "tier" : "app" }
        - cidr: 10.0.3.0/24
          az: us-east-1d
          resource_tags: { "env":"dev", "tier" : "db" }
    register: ec2vpc
#  - name: show vpc id
#    debug: var=ec2vpc
  - name: launch aws ec2 instances
    ec2:
      state: present
      key_name:
      group: vineet-is-secure
      vpc_subnet_id: "{{ec2vpc.subnets[1].id}}"
      instance_type: "{{instance_type}}"
      image: "{{image}}"
      region: "{{region}}"
      wait: true
      instance_tags:
        Name: Demo
    register: ec2
  - name: show instances
    debug: var=ec2
  - name: wait for SSH of aws ec2 instances to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=60
    with_items: ec2.instances
  - name: add aws ec2 instances to hosts
    add_host: name={{ item.public_ip }} groups=ec2hosts
    with_items: ec2.instances

- name: prepare cloud instances
  hosts: ec2hosts
  user: ubuntu
  gather_facts: true
  tasks:
  - name: install meteor
    command: curl https://install.meteor.com/ | sh
  - name: upload meteor example app
    copy: src=/Users/d046179/git/ansible_meteor/todo_example_app dest=~/
  - name: build meteor
    command: meteor build ~/todo_example_app