---
- hosts: localhost
  connection: local
  vars:
    names: mm2
    machine_type: f1-micro
    image: ubuntu-1204-precise-v20150625
    zone: europe-west1-d
    email: 547143891756-08ihrtbkhvvas21qm88kvbhv7i47mv87@developer.gserviceaccount.com
    pem_file: ~/git/ansible_meteor/pkey.pem
    project_id: fancystuff-11
  tasks:
  - name: install libcloud
    pip: name=apache-libcloud
  - name: test py import
    command: ~/git/ansible_meteor/create_instances_gce/test.py
  - name: Getting PYTHONPATH
    local_action: shell python -c 'import sys; print(":".join(sys.path))'
    register: pythonpath
  - debug:  
      msg: "PYTHONPATH: {{ pythonpath.stdout }}"
  - name: show email
    command: echo "{{email}}"  
  - name: Launch instances
    gce:
      instance_names: "{{ names }}"
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      zone: "{{ zone }}"
      service_account_email: "{{ email }}"
      project_id: "{{ project_id }}"
      pem_file: "{{ pem_file }}"

##- name: Configure instance(s)
##  hosts: launched
##  sudo: True
##  roles:
##    - my_awesome_role
##    - my_awesome_tasks
##- name: Terminate instances
##  hosts: localhost
##  connection: local
##  tasks:
##    - name: Terminate instances that were previously launched
##      local_action:
##        module: gce
##        state: 'absent'
##        instance_names: {{gce.instance_names}}
