---
- name: destruct cloud infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: vineet-michael-ansible
    instance_type: t2.micro
    image: ami-d05e75b8
    region: us-east-1
  tasks:
  - name: install boto
    pip: name=boto
  - name: delete aws ec2 auto scaling alarm/trigger
    ec2_metric_alarm:
      name: "Demo-ASG-CPU-high-alarm"
      region: "{{region}}"
      state: absent
#  - name: delete aws ec2 auto scale up policy
#    ec2_scaling_policy:
#      name: "Demo-ASG-Scale-Up"
#      asg_name: "Demo-ASG"
#      region: "{{region}}"
#      state: absent
  - name: destroy aws ec2 auto scaler
    ec2_asg:
      name: "Demo-ASG"
      region: "{{region}}"
      state: absent
  - name: destroy aws ec2 launch configuration
    ec2_lc:
      name: Demo-ASG-LC
      region: "{{region}}"
      state: absent
  - name: destroy elastic load balancer (elb)
    ec2_elb_lb:
      name: "Demo-ASG-ELB"
      region: "{{region}}"
      purge_subnets: true
      purge_zones: true
      state: absent
  - name: destroy a security group for the elb
    ec2_group:
      state: absent
      name: vineet-is-secure-asg-elb
      description: vineet is a hulk bouncer!
      region: "{{region}}"
  - name: destroy the "vineet-is-secure-asg" security group
    ec2_group:
      state: absent
      name: vineet-is-secure-asg
      description: vineet is a hulk bouncer!
      region: "{{region}}"
  - name: destroy the "env:dev" virtual private cloud (vpc)
    ec2_vpc:
      state: absent
      resource_tags: { "Name": "Demo-ASG-VPC", "env": "dev" }
      cidr_block: 10.0.0.0/16
      region: "{{region}}"

