---
- name: prepare cloud infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/common.yml
  tasks:
  - name: install boto
    pip: name=boto
  - include: tasks/vpc.yml
  - include: tasks/security-groups.yml
  - include: tasks/elb.yml
  - include: tasks/asg.yml
  - name: waiting for elb endpoint to become available
    wait_for: host={{ ec2elb.elb.dns_name }} port=80 delay=10 timeout=300 state=started
  - name: Visit the elb endpoint in your browser
    debug: msg="You can reach your metricStorageService deployment at {{ ec2elb.elb.dns_name }}"
